### ISSUE TITLE
Wrong controller device shown in pull-down (initially)

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/Indigo-miniUniFi#7] opened 2020-10-24 14:13 UTC
I added a new controller (Cloud Key G2) and renamed the device to UniFi Cloud Key G2 and the name changed in the Indigo UI device list. I then added a wireless device (my iPhone) which had a name of 'new device 2'. This was the name presented in the UniFi Controller pull-down list - the 'UniFi Cloud Key G2' wasn't listed. The device added OK and I changed the name to my iPhone's name OK. re-edited and the Controller name was still wrong, however the iPhone showed as being online. I reloaded the plugin and the issue corrected itself and the UniFi Controller name was then correctly shown.

**Comment by FlyingDiver** [comment] 2020-10-24 17:29
I think I had one other report of the Controller device not updating the name properly.  I'll look into that.

**Comment by FlyingDiver** [comment] 2020-10-24 20:31
OK, I was able to replicate this.  Not sure where the problem is.

**Comment by FlyingDiver** [comment] 2020-10-25 00:47
Fixed in 0.0.4.

**Closed by FlyingDiver** 2020-10-25 00:47 UTC
Labels: bug
